# This workflow validates, deploys, and runs the specified bundle
# within a production target named "prod".
name: 'Production deployment'

# Ensure that only a single job or workflow runs at a time.
concurrency: 1

# Trigger this workflow whenever changes are pushed to the main branch.
on:
  push:
    branches:
      - main
    paths:
      - 'bakehosue_analytics/**'

jobs:
  deploy:
    name: 'Deploy bundle'
    runs-on: ubuntu-latest

    steps:
      # Check out this repo.
      - uses: actions/checkout@v3

      # Download the Databricks CLI.
      - uses: databricks/setup-cli@main
      
      # Deploy the bundle to the "prod" target.
      - run: databricks bundle deploy
        working-directory: bakehosue_analytics
        env:
          DATABRICKS_TOKEN: ${{ secrets.SP_TOKEN }}
          DATABRICKS_BUNDLE_ENV: prod
